// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/gautamrege/gochat/api"

	mock "github.com/stretchr/testify/mock"
)

// GoChatServer is an autogenerated mock type for the GoChatServer type
type GoChatServer struct {
	mock.Mock
}

// Chat provides a mock function with given fields: _a0, _a1
func (_m *GoChatServer) Chat(_a0 context.Context, _a1 *api.ChatRequest) (*api.ChatResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *api.ChatResponse
	if rf, ok := ret.Get(0).(func(context.Context, *api.ChatRequest) *api.ChatResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ChatResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *api.ChatRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGoChatServer provides a mock function with given fields:
func (_m *GoChatServer) mustEmbedUnimplementedGoChatServer() {
	_m.Called()
}
