// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGoChatServer is an autogenerated mock type for the UnsafeGoChatServer type
type UnsafeGoChatServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGoChatServer provides a mock function with given fields:
func (_m *UnsafeGoChatServer) mustEmbedUnimplementedGoChatServer() {
	_m.Called()
}
