// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Handle
	ChatRequest
	ChatResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Handle struct {
	Name             string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host             string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port             int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Broadcastaddress string `protobuf:"bytes,4,opt,name=broadcastaddress" json:"broadcastaddress,omitempty"`
}

func (m *Handle) Reset()                    { *m = Handle{} }
func (m *Handle) String() string            { return proto.CompactTextString(m) }
func (*Handle) ProtoMessage()               {}
func (*Handle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Handle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Handle) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Handle) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Handle) GetBroadcastaddress() string {
	if m != nil {
		return m.Broadcastaddress
	}
	return ""
}

type ChatRequest struct {
	From    *Handle `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To      *Handle `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ChatRequest) Reset()                    { *m = ChatRequest{} }
func (m *ChatRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()               {}
func (*ChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatRequest) GetFrom() *Handle {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChatRequest) GetTo() *Handle {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ChatRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChatResponse struct {
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *ChatResponse) Reset()                    { *m = ChatResponse{} }
func (m *ChatResponse) String() string            { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()               {}
func (*ChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func init() {
	proto.RegisterType((*Handle)(nil), "api.Handle")
	proto.RegisterType((*ChatRequest)(nil), "api.ChatRequest")
	proto.RegisterType((*ChatResponse)(nil), "api.ChatResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoChat service

type GoChatClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type goChatClient struct {
	cc *grpc.ClientConn
}

func NewGoChatClient(cc *grpc.ClientConn) GoChatClient {
	return &goChatClient{cc}
}

func (c *goChatClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := grpc.Invoke(ctx, "/api.GoChat/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoChat service

type GoChatServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
}

func RegisterGoChatServer(s *grpc.Server, srv GoChatServer) {
	s.RegisterService(&_GoChat_serviceDesc, srv)
}

func _GoChat_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoChatServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoChat/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoChatServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoChat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GoChat",
	HandlerType: (*GoChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _GoChat_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x45, 0x5f, 0xd2, 0xbc, 0xd0, 0x4c, 0x58, 0x14, 0xaf, 0x2c, 0xba, 0xa0, 0xca, 0xaa, 0x02,
	0xd1, 0x45, 0x59, 0xf0, 0x01, 0x48, 0xc0, 0xda, 0x3f, 0x80, 0x5c, 0x3c, 0xa5, 0x95, 0x88, 0xc7,
	0x78, 0xa6, 0xff, 0x8f, 0x3c, 0x11, 0x52, 0x05, 0xab, 0xdc, 0x39, 0x13, 0xfb, 0x1e, 0x19, 0x3a,
	0x9f, 0x8e, 0x9b, 0x94, 0x49, 0xc8, 0xcc, 0x7c, 0x3a, 0x0e, 0x09, 0xda, 0x57, 0x1f, 0xc3, 0x27,
	0x1a, 0x03, 0x4d, 0xf4, 0x23, 0xda, 0x6a, 0x55, 0xad, 0x3b, 0xa7, 0xb9, 0xb0, 0x03, 0xb1, 0xd8,
	0x7a, 0x62, 0x25, 0x17, 0x96, 0x28, 0x8b, 0x9d, 0xad, 0xaa, 0xf5, 0x7f, 0xa7, 0xd9, 0xdc, 0xc2,
	0x62, 0x97, 0xc9, 0x87, 0x77, 0xcf, 0xe2, 0x43, 0xc8, 0xc8, 0x6c, 0x1b, 0x3d, 0xf3, 0x87, 0x0f,
	0x08, 0xfd, 0xd3, 0xc1, 0x8b, 0xc3, 0xaf, 0x13, 0xb2, 0x98, 0x1b, 0x68, 0xf6, 0x99, 0x46, 0xad,
	0xed, 0xb7, 0xfd, 0xa6, 0xf8, 0x4d, 0x46, 0x4e, 0x17, 0x66, 0x09, 0xb5, 0x90, 0x1a, 0xfc, 0x5a,
	0xd7, 0x42, 0xc6, 0xc2, 0xc5, 0x88, 0xcc, 0xfe, 0x03, 0xd5, 0xa7, 0x73, 0x3f, 0xe3, 0x70, 0x07,
	0x97, 0x53, 0x0d, 0x27, 0x8a, 0x8c, 0x66, 0x09, 0x5d, 0x24, 0x79, 0xdb, 0xd3, 0x29, 0x06, 0x2d,
	0x9b, 0xbb, 0x79, 0x24, 0x79, 0x2e, 0xf3, 0xf6, 0x11, 0xda, 0x17, 0x2a, 0xbf, 0x9b, 0x7b, 0x68,
	0xf4, 0xbb, 0xd0, 0xa6, 0x33, 0xd1, 0xeb, 0xab, 0x33, 0x32, 0xdd, 0x39, 0xfc, 0xdb, 0xb5, 0xfa,
	0x94, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x83, 0xc5, 0x02, 0x57, 0x01, 0x00, 0x00,
}
